name: Deploy â€” EKS load balancer controller

on:
  push:
    paths:
      - 'terraform/stacks/dev/eks/lb-controller/**'
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read

concurrency:
  group: eks-lb-controller-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tf-dev:
    name: Terraform plan/apply (eks lb controller)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      AWS_REGION: us-east-2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
      
      - name: Configurar AWS (Access Keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: show values
        run: make show OS_TARGET=linux

      - name: terraform init
        run: make tf-lb-controller.init OS_TARGET=linux

      - name: terraform plan
        run: make tf-lb-controller.plan OS_TARGET=linux

      - name: terraform apply
        run: make tf-lb-controller.apply OS_TARGET=linux
