name: EKS — Cluster

on:
  push:
    paths:
      - 'terraform/stacks/dev/eks/cluster/**'
  workflow_dispatch:
    inputs:
      action:
        description: "apply | destroy"
        required: true
        default: "apply"
        type: choice
        options: ["apply","destroy"]

permissions:
  id-token: write
  contents: read

concurrency:
  group: eks-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tf-dev:
    name: Terraform (${{ github.event_name == 'push' && 'apply' || inputs.action }}) (eks/dev)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      AWS_REGION: us-east-2
    steps:
      - uses: actions/checkout@v4

      - name: Build terraform image
        run: make build
        env:
          IMAGE: acme-terraform:latest
      
      - name: Configurar AWS (Access Keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: show values
        run: make show OS_TARGET=linux

      - name: terraform init
        run: make tf-eks.init OS_TARGET=linux

      # APPLY: corre en push o si en dispatch elegiste "apply"
      - name: terraform apply
        if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.action == 'apply') }}
        run: make tf-eks.apply OS_TARGET=linux

      # DESTROY: solo en dispatch con action=destroy (sin confirmación)
      - name: terraform destroy
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.action == 'destroy' }}
        run: make tf-eks.destroy OS_TARGET=linux
