name: Deploy â€” EKS (dev)

on:
  push:
    paths:
      - 'terraform/stacks/dev/eks/**'

permissions:
  id-token: write
  contents: read

concurrency:
  group: eks-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tf-dev:
    name: Terraform plan/apply (eks/dev)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform/stacks/dev/eks
    env:
      AWS_REGION: us-east-2 # ajusta si corresponde
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Configurar AWS (OIDC -> rol dev)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_DEV }}
          aws-region: ${{ env.AWS_REGION }}

      - name: terraform init
        run: make tf.init STACK=eks

      - name: terraform plan
        run: make tf.plan STACK=eks 

      - name: terraform apply
        run: make tf.apply STACK=eks