name: Kubernetes - manifest

on:
  push:
    paths:
      - 'k8n/**'
  workflow_dispatch:
    inputs:
      action:
        description: "apply | delete"
        required: true
        default: "apply"
        type: choice
        options: ["apply","delete"]

permissions:
  id-token: write
  contents: read

concurrency:
  group: k8n-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tf-dev:
    name: K8n (${{ github.event_name == 'push' && 'apply' || inputs.action }})
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      AWS_REGION: us-east-2
      CLUSTER_NAME: eks-acme-dev-us-east-2

    steps:
      - uses: actions/checkout@v4

      - name: Configurar AWS (Access Keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Configurar kubeconfig de EKS
        run: |
          aws eks update-kubeconfig --name "${CLUSTER_NAME}" --region "${AWS_REGION}"
          kubectl version --client --output=yaml
          kubectl get nodes

      # ===== APPLY (por push o input 'apply') =====
      - name: apply namespace
        if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.action == 'apply') }}
        run: kubectl apply -f ./k8n/namespace.yaml

      - name: apply deployment
        if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.action == 'apply') }}
        run: kubectl apply -f ./k8n/deployment.yaml

      - name: apply service
        if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.action == 'apply') }}
        run: kubectl apply -f ./k8n/service.yaml

      - name: apply ingress
        if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.action == 'apply') }}
        run: kubectl apply -f ./k8n/ingress.yaml

      - name: apply hpa
        if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.action == 'apply') }}
        run: kubectl apply -f ./k8n/hpa.yaml

      - name: ver recursos (demo)
        if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.action == 'apply') }}
        run: |
          kubectl -n demo get all
          kubectl -n demo get pods
          kubectl -n demo describe ingress web

      # ===== DELETE (solo por input 'delete') =====
      - name: delete hpa
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.action == 'delete' }}
        run: kubectl delete -f ./k8n/hpa.yaml --ignore-not-found

      - name: delete ingress
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.action == 'delete' }}
        run: kubectl delete -f ./k8n/ingress.yaml --ignore-not-found

      - name: delete service
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.action == 'delete' }}
        run: kubectl delete -f ./k8n/service.yaml --ignore-not-found

      - name: delete deployment
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.action == 'delete' }}
        run: kubectl delete -f ./k8n/deployment.yaml --ignore-not-found

      - name: delete namespace (al final)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.action == 'delete' }}
        run: kubectl delete -f ./k8n/namespace.yaml --ignore-not-found
