name: Deploy â€” Networking

on:
  push:
    paths:
      - 'terraform/stacks/dev/network/vpc/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: networking-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tf-dev:
    name: Terraform plan/apply (networking)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      AWS_REGION: us-east-2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
      
      - name: Build terraform image
        run: make build
        env:
          IMAGE: acme-terraform:latest

      - name: Configurar AWS (Access Keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: terraform init
        run: make tf-network.init AWS_PROFILE=default

      - name: terraform plan
        run: make tf-network.plan AWS_PROFILE=default

      - name: terraform apply
        run: make tf-network.apply AWS_PROFILE=default
